'''

Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

'''

def main():
    evens = 0
    prev = 1
    current = 2

    while (current<4000000):
        if not (current % 2):
            evens += current 
        temp = current + prev
        prev = current
        current = temp

    print("Sum of the even numbers in the Fibonacci under 4,000,000: ", evens)

if __name__ == "__main__":
    main()